# Generated by Django 4.0.2 on 2022-02-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_alter_story_options_story_published_story_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(related_name='story', to='story.Tag'),
        ),
    ]
