# Generated by Django 4.0.2 on 2022-02-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_story_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='locationLat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='locationLong',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
