# Generated by Django 4.0.2 on 2022-02-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_story_locationlat_story_locationlong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='locationLat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='locationLong',
            new_name='longitude',
        ),
    ]
