# Generated by Django 4.0.2 on 2022-02-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_rename_locationlat_story_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(to='story.Tag'),
        ),
    ]
