# Generated by Django 4.0.2 on 2022-02-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_alter_story_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title_length',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
