# Generated by Django 4.0.2 on 2022-02-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_alter_story_title_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='created_at_month',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
