# Generated by Django 4.0.2 on 2022-02-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_alter_story_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updated_at',
        ),
    ]
