# Generated by Django 4.0.2 on 2022-03-01 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0014_secretquestion_secretquestionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretquestion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to=settings.AUTH_USER_MODEL),
        ),
    ]
