# Generated by Django 4.0.2 on 2022-03-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0015_secretquestion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretquestion',
            name='user',
        ),
    ]
