# Generated by Django 4.0.2 on 2022-03-16 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0016_remove_secretquestion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretquestionanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='story.secretquestion'),
        ),
    ]
